import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";

/* Flat config, generated by `npx @next/codemod@latest next-lint-to-eslint-cli`
 * and then hand-edited for the ignore list below.
 *
 * Why it exists: Next 16 removed `next lint`, which left `npm run lint`
 * resolving `lint` as a directory and failing with "no such directory:
 * frontend/lint" — broken for long enough that the root CLAUDE.md documented
 * it as a known defect.
 *
 * The two shared configs are the codemod's output verbatim. Everything after
 * them is the part that needed a human: the codemod's default ignores cover
 * `.next/`, `out/` and `build/`, but not the two large generated trees this
 * project actually has, and without them `eslint .` reports ~8,940 problems in
 * files nobody here writes — which is the same as reporting nothing at all.
 */
const eslintConfig = [
  ...nextCoreWebVitals,
  ...nextTypescript,
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "out/**",
      "build/**",
      "next-env.d.ts",

      /* The Capacitor native project. Every one of the 80 `.js` files under
         here is either a Gradle build intermediate or the web bundle
         `cap sync` copies into `app/src/main/assets/public/` — Next's hashed
         chunks plus the Cordova shims. There is no hand-written JavaScript in
         the tree, and the sources it mirrors are already linted where they
         actually live. It alone accounted for 8,940 of the 8,947 problems the
         first post-codemod run reported. */
      "android/**",

      /* Written by `scripts/build-sw.mjs` after every build, from
         `sw/sw.template.js`, carrying that build's content-hashed chunk names.
         It is gitignored for exactly that reason. The template is the source
         and is linted; this is its output. */
      "public/sw.js",
    ],
  },

  /* `/offline` is served from the service-worker cache with the network down,
     where a client-side RSC navigation cannot resolve — so its "Try again"
     control and its footer are plain `<a>` on purpose, and that decision is
     recorded in docs/frontend/legal-offline-routes.md. The rule is right about
     every other route and stays on for them; disabling it here rather than
     inline keeps the reasoning next to the rest of the config, where the next
     person to read this file will find it. */
  {
    files: ["app/offline/**"],
    rules: { "@next/next/no-html-link-for-pages": "off" },
  },
];

export default eslintConfig;
